### ISSUE TITLE
Date() displayed wrong

### ISSUE THREAD

**Issue by pavlem** [IBM-Swift/Swift-JWT#25]
Hello, 
I am using a "hs256" algorithm and, when I make creating a clame, my Date, for example `Date()` displays correctly in the code, but when I put it in a claim like 
`var jwt = JWT(claims: AdminClaims(sub: "Kitura", isAdmin: true, exp: Date()))` 
I get a weird time of year 1988 which I can see when I paste the complete JWT string to https://jwt.io/ 

I had no problems with other libraries recommended from JWT in this sense, but this is most up to date and I would like to use it if this is solvable. 

for example this is the code

        let myHeader = Header(kid: "KeyID1")

        struct AdminClaims: Claims {
            var sub: String
            var isAdmin: Bool
            var exp: Date
        }
        
        let expDate = Date(timeIntervalSinceNow: 60)
        var jwt = JWT(header: myHeader, claims: AdminClaims(sub: "Kitura", isAdmin: true, exp: expDate))

        let secretData = "test123".data(using: .utf8)!
        let jwtSigner = JWTSigner.hs256(key: secretData)
        let signedJWT = try! jwt.sign(using: jwtSigner)

and I get this jwt string

`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6IktleUlEMSJ9.eyJzdWIiOiJLaXR1cmEiLCJpc0FkbWluIjp0cnVlLCJleHAiOjU2ODcxNDEwNi40OTkwOTk5N30.55r0oXo4hPDLbErDpZgdSaUGpIWylPuz9YpCcGywrO8`

**Comment by Andrew-Lees11** [comment]
Hello @pavlem 
Thank you for raising this issue. The JWT's are encoded using JSONEncoder and JSONDecoder which use 00:00:00 UTC on 1 January 2001 as the default reference date. The [JWT specs](https://tools.ietf.org/html/rfc7519#section-2) specify that dates should be encoded/decoded as seconds since 1970 so this is a bug.
 A pull request changing this behavior has been raised and we will look to implement this change in a minor release.
This update will invalidate the dates on any existing JWT's which will have to be created again using the new encoding.

**Comment by Andrew-Lees11** [comment]
This fix has been merged and tagged in version [3.1.1](https://github.com/IBM-Swift/Swift-JWT/releases/tag/3.1.1). As such I am closing this issue.
