### ISSUE TITLE
Issued At claim is greater than the current time

### ISSUE THREAD

**Issue by david-canty** [IBM-Swift/Swift-JWT#31]
I'm occasionally getting the error 'Issued At claim is greater than the current time' when validating JWT claims.

I'm guessing this is because of clock skew because most of the time it works. However, occasionally this error crops up and breaks access to my API from my iOS app.

Is there a way of disabling IAT validation but leaving the rest of the validation in place?

For information, I'm validating a Firebase user token.

**Comment by Andrew-Lees11** [comment]
@david-canty If this is due to clock skew we could add a "leeway" parameter which you could set on validateJWT. This would allow you to set a length of time which it will still validate the JWT even if the iat is before the current time.
If I raise a PR with this addition would you be able to test it and see if it solves your issue?

**Comment by Andrew-Lees11** [comment]
@david-canty I have raised a pull request adding a leeway parameter to the validate claims function. 
Are you still having this issue and if so would be you be able to test that this fixes it?

**Comment by Andrew-Lees11** [comment]
Closing now the leeway parameter has been merged and tagged in version 3.2
