### ISSUE TITLE
Is it possible to generate a single time use token?

### ISSUE THREAD

**Issue by diuming** [IBM-Swift/Swift-JWT#58]
Hi,
Is it possible to generate a `single time` use token?

environment
---
OS: macOS 14.4
Xcode: 10.2.1

thanks

**Comment by Andrew-Lees11** [comment]
JWTs are stateless so the single use behavior would have to come from the server. Why would you like it to be single use? [This article](https://www.jbspeakr.cc/howto-single-use-jwt/) describes a method for password reset by using the state (Hashed password) that will be changed by the request. Otherwise you can use the "jti" claim to assign a unique identifier that can be checked by the server to see if the JWT has already been used.
