### ISSUE TITLE
Is it possible to add a ClaimSet class that is generic and allow adding new claims for multiple apps requirement.

### ISSUE THREAD

**Issue by awadodeh** [IBM-Swift/Swift-JWT#61]
Is it possible to add a ClaimSet class that is generic and allow adding new claims for multiple apps requirement?

**Comment by Andrew-Lees11** [comment]
Hello @awadodeh 
I'm not quite sure what you mean by a ClaimSet class. The JWT class is already generic over the Claims class. You can define your own type that conforms to Claims that has the fields you define. 
This should already allow you to add new custom claims for your own app requirements.

**Comment by awadodeh** [comment]
Hello Andrew! 

What I am trying to say is basically making the library generic to accept user defined claims without having to declare new types for each different app requirement. 

For example, if you have a micro service and a web/mobile app that are consuming the service, and you need to add a new claim for your JWT. You would need to create a new type like 
```
struct MyClaims: Claims {
    let iss: String
    let sub: String
    let exp: Date
    let admin: Bool
    let accessGroups: [String]
}
let myClaims = MyClaims(iss: "Kitura", sub: "John", exp: Date(timeIntervalSinceNow: 3600), admin: true, accessGroups: ["all"])
```
This will also require that you have access to MyClaims, in all the clients(webapp, mobile ).
Now if a change was made to the MyClaims, this needs to propagate to other clients are using it.

My thought is what if we make Claims generic that can accept new claims and detect their type without having the need to create MyClaims struct, or maybe introduce a new struct in the library that does that, i.e `ClaimSet` which can accept these new types.

**Comment by Andrew-Lees11** [comment]
Hey
So I think you are requesting one of the following three features:

1. When decoding the Claims JSON, leave the claims undefined such as a [String: Any]. This would remove the requirement to define a struct, but removes the type safety since you would have to access each field as a string vs the dictionary and cast to the required type.
2. Create a JWT that has a set of possible claims and will decode to the specific one depending on the JSON provided. You could implement this with the current system with an enum/array of possible types and looping through it as you try and decode
3. Dynamically generate a Struct in Swift based on the JSON you receive. I'm not sure how you would do this since swift is statically typed and even if you did you wouldn't know what fields are available to access. 

I would hope that you can share models between client and server either by matching existing models or using the same models on both ends. If there are extra fields in the JSON than your model the JWT should still be able to be decoded and you can always add optional fields if some clients will not require all the properties. 

If you are able to suggest an implementation of this `ClaimSet` I would be happy to test and prototype it.
